--
-- Table structure for table `encuesta_grupo_preguntas`
--

DROP TABLE IF EXISTS `encuesta_grupo_preguntas`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `encuesta_grupo_preguntas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombreGrupo` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_C3917B5DE088E3B` (`nombreGrupo`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `encuesta_grupo_preguntas`
--

LOCK TABLES `encuesta_grupo_preguntas` WRITE;
/*!40000 ALTER TABLE `encuesta_grupo_preguntas` DISABLE KEYS */;
INSERT INTO `encuesta_grupo_preguntas` VALUES (23,'4'),(24,'5'),(20,'APLICA CONTROL DE FAUNA?'),(13,'APLICA LEY N° 3166 DE ACEITES VEGETALES USADOS (AVUs)?'),(19,'APLICA LEY N° 5991 - GESTIÓN AMBIENTAL DE PILAS EN DESUSO?'),(6,'APLICA NORMATIVA DE VERTIDOS INDUSTRIALES LÍQUIDOS?'),(17,'APLICA NORMATIVA RES N°341/2016 (RES N° 29/2018) - BOLSAS PLÁSTICAS?'),(9,'APLICA REGISTRO DE ACTIVIDADES CATALOGADAS COMO POTENCIALMENTE CONTAMINANTES POR RUIDOS Y VIBRACIONES (RAC)?'),(2,'DOCUMENTACIÓN'),(18,'ENTREGA SORBETES  (RES. N° 816/2019)?'),(3,'EVALUACIÓN DE IMPACTO AMBIENTAL Ley N° 123'),(7,'GENERA EMISIONES GASEOSAS?'),(5,'GENERA RESIDUOS PATOGÉNICOS?'),(4,'GENERA RESIDUOS PELIGROSOS?'),(8,'HAY TRASCENDENCIA DE OLOR/CALOR?'),(1,'INFORMACIÓN DEL ADMINISTRADO/ESTABLECIMIENTO/EVENTO'),(12,'POSEE ACOPIO DE COMBUSTIBLES?'),(16,'POSEE NATATORIO?'),(15,'REGISTRO PÚBLICO DE LAVADEROS, LAVANDERÍAS Y TRANSPORTISTAS DE ROPA HOSPITALARIA.'),(22,'RESUMEN OPERATIVO'),(11,'SE REALIZA MEDICIÓN DE VIBRACIONES?'),(10,'SE REALIZAN MEDICIONES DE RUIDO?'),(21,'SE VERIFICAN OTRAS FALTAS?'),(14,'TINTORERÍAS - LIMPIEZA A SECO'),(25,'VIEJA ENCUESTA');
/*!40000 ALTER TABLE `encuesta_grupo_preguntas` ENABLE KEYS */;
UNLOCK TABLES;

