--
-- Table structure for table `tipo_cedula`
--

DROP TABLE IF EXISTS `tipo_cedula`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tipo_cedula` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `TipoCedula` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_EE4A6DF8BF86EB52` (`TipoCedula`)
) ENGINE=InnoDB AUTO_INCREMENT=87 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `tipo_cedula`
--

LOCK TABLES `tipo_cedula` WRITE;
/*!40000 ALTER TABLE `tipo_cedula` DISABLE KEYS */;
INSERT INTO `tipo_cedula` VALUES (33,'AVISO DE VISITA SIN INSPECCION'),(1,'AVUS'),(2,'CAA'),(30,'CEDULA DE CITACION'),(28,'CERFITICADO LIMPIEZA de TANQUE de AGUA'),(27,'CERTIFICADO DESINFECCION'),(3,'CLUB DEPORTIVO'),(85,'DERROCHE DE AGUA'),(17,'DGET'),(35,'DGPOLEA'),(20,'EFLUENTES'),(31,'EMPRESAS DE FUMIGACION/TANQUES'),(14,'FUENTES MOVILES'),(86,'INTIMACION DGCONTA'),(34,'INTIMACION-INMEDIATA'),(23,'MATAFUEGOS'),(6,'NOCTURNIDAD'),(21,'NOTIFICACIONES'),(29,'OLORES'),(11,'OTROS'),(12,'PERSONAL'),(5,'PREDIO'),(7,'PROCTORES EVENTOS'),(24,'PRODUCTORAS'),(16,'PRORROGA'),(25,'RAC'),(22,'RES. PATOGENICOS'),(18,'RES. PELIGROSOS.'),(15,'ROPA DE TRABAJO'),(8,'ROPA HOSPITALARIA'),(19,'RUIDOS'),(4,'SEGURO AMB. OBLIG'),(13,'SITIOS CONTAMINADOS'),(9,'SUACI'),(32,'SUPERMERCADO');
/*!40000 ALTER TABLE `tipo_cedula` ENABLE KEYS */;
UNLOCK TABLES;
